int Led1 = 2;
int Led2 = 3;
int Led3 = 4;
int Led4 = 5;
int Led5 = 6;
int Led6 = 7;
int Led7 = 8;
int Led8 = 9;
int Led9 = 10;
int Led10 = 11;

void setup() {
  pinMode(Led1, OUTPUT);
  pinMode(Led2, OUTPUT);
  pinMode(Led3, OUTPUT);
  pinMode(Led4, OUTPUT);
  pinMode(Led5, OUTPUT);
  pinMode(Led6, OUTPUT);
  pinMode(Led7, OUTPUT);
  pinMode(Led8, OUTPUT);
  pinMode(Led9, OUTPUT);
  pinMode(Led10, OUTPUT);
}

void loop() {
  //Luces seriales
  digitalWrite(Led1, HIGH);
  delay(60);  
  digitalWrite(Led1, LOW);
  delay(60);
  digitalWrite(Led2, HIGH);
  delay(60);  
  digitalWrite(Led2, LOW);
  delay(60);
  digitalWrite(Led3, HIGH);
  delay(60);  
  digitalWrite(Led3, LOW);
  delay(60);
  digitalWrite(Led4, HIGH);
  delay(60);  
  digitalWrite(Led4, LOW);
  delay(60);
  digitalWrite(Led5, HIGH);
  delay(60);  
  digitalWrite(Led5, LOW);
  delay(60);
  digitalWrite(Led6, HIGH);
  delay(60);  
  digitalWrite(Led6, LOW);
  delay(60);
  digitalWrite(Led7, HIGH);
  delay(60);  
  digitalWrite(Led7, LOW);
  delay(60);
  digitalWrite(Led8, HIGH);
  delay(60);  
  digitalWrite(Led8, LOW);
  delay(60);
  digitalWrite(Led9, HIGH);
  delay(60);  
  digitalWrite(Led9, LOW);
  delay(60);
  digitalWrite(Led10, HIGH);
  delay(60);  
  digitalWrite(Led10, LOW);
  delay(3000); 

  // dos leds de izquierda a derecha
  digitalWrite(Led1, HIGH);
  digitalWrite(Led2, HIGH);
  delay(1000);  
  digitalWrite(Led1, LOW);
  digitalWrite(Led2, LOW);
  delay(60);
  digitalWrite(Led3, HIGH);
  digitalWrite(Led4, HIGH);
  delay(1000);  
  digitalWrite(Led3, LOW);
  digitalWrite(Led4, LOW);
  delay(60);
  digitalWrite(Led5, HIGH);
  digitalWrite(Led6, HIGH);
  delay(1000);  
  digitalWrite(Led5, LOW);
  digitalWrite(Led6, LOW);
  delay(60);
  digitalWrite(Led7, HIGH);
  digitalWrite(Led8, HIGH);
  delay(1000);  
  digitalWrite(Led7, LOW);
  digitalWrite(Led8, LOW);
  delay(60);
  digitalWrite(Led9, HIGH);
  digitalWrite(Led10, HIGH);
  delay(1000);  
  digitalWrite(Led9, LOW);
  digitalWrite(Led10, LOW);
  delay(3000);

  //Dos luces de izquierda a derecha y derecha a izquierda
  digitalWrite(Led1, HIGH);
  digitalWrite(Led2, HIGH);
  delay(1000);  
  digitalWrite(Led1, LOW);
  digitalWrite(Led2, LOW);
  delay(60);
  digitalWrite(Led3, HIGH);
  digitalWrite(Led4, HIGH);
  delay(1000);  
  digitalWrite(Led3, LOW);
  digitalWrite(Led4, LOW);
  delay(60);
  digitalWrite(Led5, HIGH);
  digitalWrite(Led6, HIGH);
  delay(1000);  
  digitalWrite(Led5, LOW);
  digitalWrite(Led6, LOW);
  delay(60);
  digitalWrite(Led7, HIGH);
  digitalWrite(Led8, HIGH);
  delay(1000);  
  digitalWrite(Led7, LOW);
  digitalWrite(Led8, LOW);
  delay(60);
  digitalWrite(Led9, HIGH);
  digitalWrite(Led10, HIGH);
  delay(1000);  
  digitalWrite(Led9, LOW);
  digitalWrite(Led10, LOW);
  delay(60);
  
  digitalWrite(Led8, HIGH);
  digitalWrite(Led7, HIGH);
  delay(1000);  
  digitalWrite(Led8, LOW);
  digitalWrite(Led7, LOW);
  delay(60);
  digitalWrite(Led6, HIGH);
  digitalWrite(Led5, HIGH);
  delay(1000);  
  digitalWrite(Led6, LOW);
  digitalWrite(Led5, LOW);
  delay(60);
  digitalWrite(Led4, HIGH);
  digitalWrite(Led3, HIGH);
  delay(1000);  
  digitalWrite(Led4, LOW);
  digitalWrite(Led3, LOW);
  delay(60);
  digitalWrite(Led2, HIGH);
  digitalWrite(Led1, HIGH);
  delay(1000);  
  digitalWrite(Led2, LOW);
  digitalWrite(Led1, LOW);
  delay(60);
  
  digitalWrite(Led3, HIGH);
  digitalWrite(Led4, HIGH);
  delay(1000);  
  digitalWrite(Led3, LOW);
  digitalWrite(Led4, LOW);
  delay(60);
  digitalWrite(Led5, HIGH);
  digitalWrite(Led6, HIGH);
  delay(1000);  
  digitalWrite(Led5, LOW);
  digitalWrite(Led6, LOW);
  delay(60);
  digitalWrite(Led7, HIGH);
  digitalWrite(Led8, HIGH);
  delay(1000);  
  digitalWrite(Led7, LOW);
  digitalWrite(Led8, LOW);
  delay(60);
  digitalWrite(Led9, HIGH);
  digitalWrite(Led10, HIGH);
  delay(1000);  
  digitalWrite(Led9, LOW);
  digitalWrite(Led10, LOW);
  delay(60);

  digitalWrite(Led10, HIGH);
  digitalWrite(Led9, HIGH);
  delay(1000);  
  digitalWrite(Led10, LOW);
  digitalWrite(Led9, LOW);
  delay(60);
  digitalWrite(Led8, HIGH);
  digitalWrite(Led7, HIGH);
  delay(1000);  
  digitalWrite(Led8, LOW);
  digitalWrite(Led7, LOW);
  delay(60);
  digitalWrite(Led6, HIGH);
  digitalWrite(Led5, HIGH);
  delay(1000);  
  digitalWrite(Led6, LOW);
  digitalWrite(Led5, LOW);
  delay(60);
  digitalWrite(Led4, HIGH);
  digitalWrite(Led3, HIGH);
  delay(1000);  
  digitalWrite(Led4, LOW);
  digitalWrite(Led3, LOW);
  delay(60);
  digitalWrite(Led2, HIGH);
  digitalWrite(Led1, HIGH);
  delay(1000);  
  digitalWrite(Led2, LOW);
  digitalWrite(Led1, LOW);
  delay(60);
}
